
steps:
  # Installer les dépendances
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'backend-gcp/microservice-football'

  # Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oracle-prediction-football:$COMMIT_SHA', '.']
    dir: 'backend-gcp/microservice-football'

  # Pousser l'image vers Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/oracle-prediction-football:$COMMIT_SHA']

  # Déployer sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'oracle-prediction-football' # Nom de votre service Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/oracle-prediction-football:$COMMIT_SHA'
      - '--region'
      - 'europe-west1' # Région à adapter
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Important pour les services publics, sinon à retirer si géré par API Gateway

images:
  - 'gcr.io/$PROJECT_ID/oracle-prediction-football:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
