swagger: '2.0'
info:
  title: 'Oracle Prediction API'
  description: 'API for football predictions and tickets'
  version: '1.0.0'
schemes:
  - 'https'
produces:
  - 'application/json'

x-google-backend:
  address: https://oracle-prediction-football-321557095918.europe-west1.run.app

paths:
  /api/{path=**}:
    get:
      summary: 'Proxy all GET requests to the backend'
      operationId: 'proxy-get'
      parameters:
        - in: path
          name: path
          type: string
          required: true
      security:
        - firebase: []
      responses:
        '200':
          description: 'A successful response'
    # AJOUT DE CETTE SECTION POUR LE CORS
    options:
      summary: 'CORS support'
      operationId: 'cors-handler'
      parameters:
        - name: path
          in: path
          type: string
          required: true
      responses:
        '204':
          description: 'No Content response for CORS preflight.'
          headers:
            Access-Control-Allow-Origin:
              type: 'string'
            Access-Control-Allow-Methods:
              type: 'string'
            Access-Control-Allow-Headers:
              type: 'string'
            Access-Control-Max-Age:
              type: 'string'

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"