swagger: '2.0'
info:
  title: 'Oracle Prediction API'
  description: 'API for football predictions and tickets'
  version: '1.0.0'
schemes:
  - 'https'
produces:
  - 'application/json'

x-google-backend:
  address: https://oracle-prediction-football-321557095918.europe-west1.run.app 

paths:
  # La syntaxe corrigée pour capturer tous les sous-chemins
  /api/{path=**}:
    get:
      summary: 'Proxy all GET requests to the backend'
      operationId: 'proxy-get'
      # Cette section est nécessaire pour déclarer la variable utilisée dans le chemin
      parameters:
        - in: path
          name: path
          type: string
          required: true
      security:
        - firebase: []
      responses:
        '200':
          description: 'A successful response'

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"