swagger: '2.0'
info:
  title: Oracle Prediction API (Correct CORS)
  version: '10.0.6'
schemes:
  - https
produces:
  - application/json

# La sécurité est définie au niveau supérieur
security:
  - firebase: []

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: implicit
    type: oauth2
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"

paths:
  # =================================================================
  # DÉBUT DE LA SOLUTION DE L'ARTICLE
  # Cette section "catch-all" intercepte TOUTES les requêtes
  # OPTIONS et y répond directement depuis la passerelle.
  # =================================================================
  /{proxy+}:
    options:
      summary: CORS preflight handler
      operationId: cors-preflight
      # Pas de sécurité sur la requête OPTIONS
      security: []
      responses:
        '204':
          description: No content
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
            Access-Control-Max-Age:
              type: string
  # =================================================================
  # FIN DE LA SOLUTION
  # =================================================================
  
  /api/predictions:
    get:
      summary: Get daily predictions
      operationId: get-predictions
      # La sécurité est héritée du niveau supérieur
      x-google-backend:
        address: https://oracle-prediction-football-co4b4rv5mq-ew.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: List of predictions
        'default':
          description: Default response from backend

  /api/tickets:
    get:
      summary: Get daily tickets
      operationId: get-tickets
      # La sécurité est héritée du niveau supérieur
      x-google-backend:
        address: https://oracle-prediction-football-co4b4rv5mq-ew.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: List of tickets
        'default':
          description: Default response from backend