swagger: '2.0'
info:
  title: 'Oracle Prediction API (Passthrough Strategy)'
  version: '10.0.1'
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"

paths:
  # Règle "catch-all" pour transférer TOUTES les requêtes au backend
  /{proxy+}:
    # Définition du backend pour toutes les méthodes de ce chemin
    x-google-backend:
      address: https://oracle-prediction-football-321557095918.europe-west1.run.app
      path_translation: APPEND_PATH_TO_ADDRESS

    # AJOUT IMPORTANT : Autoriser les requêtes preflight OPTIONS à passer
    options:
      summary: "CORS preflight passthrough"
      operationId: "cors-preflight-passthrough-all"
      # Les requêtes OPTIONS n'ont pas de sécurité, c'est crucial
      security: []
      responses:
        '204':
          description: "No Content. CORS preflight response."

    # Vos autres méthodes (GET, POST, etc.) restent inchangées
    get:
      summary: "Generic GET with security"
      operationId: "get-passthrough"
      security:
        - firebase: []
      responses:
        'default':
          description: "Default GET response from backend"
    # Ajoutez ici d'autres méthodes (post, put, delete...) si nécessaire