swagger: '2.0'
info:
  title: Oracle Prediction API (Final Stable)
  version: '4.0.0' # Nouvelle version finale
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"

paths:
  /api/predictions:
    get:
      summary: Get daily predictions
      operationId: get-predictions
      security:
        - firebase: []
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response

  /api/tickets:
    get:
      summary: Get daily tickets
      operationId: get-tickets
      security:
        - firebase: []
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response

x-google-cors:
  allow_origin:
    - "https://oracle-prediction-app.web.app"
    - "https://oracle-prediction-app.firebaseapp.com"
  allow_methods:
    - "GET"
    - "OPTIONS"
  allow_headers:
    - "Authorization"
    - "Content-Type"