swagger: '2.0'
info:
  title: Oracle Prediction API (Stable)
  version: '2.0.0'
schemes:
  - https
produces:
  - application/json

security:
  - firebase: []

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: implicit
    type: oauth2
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"

paths:
  /api/predictions:
    get:
      summary: Get daily predictions
      operationId: get-predictions
      x-google-backend:
        address: https://oracle-prediction-football-co4b4rv5mq-ew.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
    options:
      summary: CORS support
      operationId: cors-predictions
      security: []
      responses:
        '204':
          description: "No Content"

  /api/tickets:
    get:
      summary: Get daily tickets
      operationId: get-tickets
      x-google-backend:
        address: https://oracle-prediction-football-co4b4rv5mq-ew.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
    options:
      summary: CORS support
      operationId: cors-tickets
      security: []
      responses:
        '204':
          description: "No Content"

x-google-cors:
  allow_origin:
    - "https://oracle-prediction-app.firebaseapp.com"
    - "https://oracle-prediction-app.web.app"
  allow_methods:
    - GET
    - OPTIONS
  allow_headers:
    - Authorization
    - Content-Type