# swagger.yaml - Version de débogage
swagger: '2.0'
info:
  title: 'Oracle Prediction API (Debug CORS)'
  version: '3.0.0'
schemes:
  - https
produces:
  - application/json

paths:
  /api/tickets:
    get:
      summary: "Get tickets"
      operationId: "getTickets"
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: "Success"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: "CORS support for tickets"
      operationId: "corsTickets"
      responses:
        '204':
          description: "No Content response for CORS preflight."
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"