# Contenu complet pour votre nouveau fichier swagger.yaml
swagger: '2.0'
info:
  title: 'Oracle Prediction API (CORS Fixed)'
  version: '2.0.1'
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"

paths:
  /api/tickets:
    get:
      summary: "Get tickets"
      operationId: "getTickets"
      security:
        - firebase: []
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
      responses:
        '200':
          description: "Success"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: "CORS support for tickets"
      operationId: "corsTickets"
      responses:
        '204':
          description: "No Content response for CORS preflight."
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Max-Age:
              type: "string"

  /api/predictions:
    get:
      summary: "Get predictions"
      operationId: "getPredictions"
      security:
        - firebase: []
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
      responses:
        '200':
          description: "Success"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: "CORS support for predictions"
      operationId: "corsPredictions"
      responses:
        '204':
          description: "No Content response for CORS preflight."
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Max-Age:
              type: "string"

  /run-all-jobs:
    get:
      summary: "Run all jobs"
      operationId: "runAllJobs"
      security:
        - firebase: []
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
      responses:
        '202':
          description: "Jobs started"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: "CORS support for jobs endpoint"
      operationId: "corsJobs"
      responses:
        '204':
          description: "No Content response for CORS preflight."
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Max-Age:
              type: "string"