# swagger.yaml - Stratégie de transmission des requêtes OPTIONS
swagger: '2.0'
info:
  title: 'Oracle Prediction API (Passthrough Fix)'
  version: '6.0.0'
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"

paths:
  # On utilise un "wildcard" pour dire que TOUS les chemins sont gérés par le backend
  /{proxy+}:
    get:
      summary: "Proxy GET requests"
      operationId: "proxy-get"
      security:
        - firebase: []
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: "A successful response from the backend"
        '404':
          description: "Not found response from the backend"
        '500':
          description: "Server error from the backend"
    
    # On transmet aussi TOUTES les requêtes OPTIONS au backend, sans sécurité
    options:
      summary: "CORS preflight"
      operationId: "cors-preflight"
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: "CORS preflight response"