swagger: '2.0'
info:
  title: 'Oracle Prediction API (Passthrough Strategy)'
  version: '10.0.1' # Mise à jour de la version pour refléter les changements
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/oracle-prediction-app"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "oracle-prediction-app"

paths:
  /api/tickets:
    options:
      summary: "CORS preflight for /api/tickets"
      operationId: "cors-preflight-tickets"
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: "CORS preflight response"
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
    get:
      summary: "Get tickets"
      operationId: "get-tickets"
      security:
        - firebase: []
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: query
          name: date
          type: string
          required: false
      responses:
        '200':
          description: "Successful response"
          schema:
            type: object
  /{proxy+}:
    options:
      summary: "CORS preflight passthrough"
      operationId: "cors-preflight-passthrough"
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        'default':
          description: "CORS preflight response from backend"
    get:
      summary: "Generic GET with security"
      operationId: "get-passthrough"
      security:
        - firebase: []
      x-google-backend:
        address: https://oracle-prediction-football-321557095918.europe-west1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        'default':
          description: "Default GET response from backend"